apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: proyectosqa
build:
  artifacts:
  - image: selenium/hub
    jib: {}
  local: {}

deploy:
  kubectl:
    manifests:
    - k8s-deployment.yaml
    - k8s-pod.yaml
    - k8s-rep.yaml
    - k8s-service.yaml
